version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
       # The port that is exposed to your machine is before the colon
       # The port after the colon is the internal port that it listens to
     - "8000:8000"
    # You can persist your data by mounting it.
    # Similar to the port you'll insert the "real" mounting point before the colon, 
    # and the internal after it. Make sure that the internal mount point corresponds with
    # the path in your app. The backend source code will be mounted under /app/
    # volumes:
      # - ./:/app
    environment:
      - ENVIRONMENT=production # set to development to enable debug mode
      - LOG_LEVEL=INFO # Set the general log level, more fine grained can also be set
      - LOG_FILE=/app/logs/backend.log # path to log file, make sure to also mount the folder
    command: "poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped
